# Generated by Django 2.2.7 on 2019-11-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('founded', models.DateField()),
                ('founder', models.TextField()),
                ('headquater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HW1.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('OS', models.CharField(choices=[('I', 'iOS'), ('A', 'Android')], max_length=1)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(help_text='in Euros')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HW1.Producer')),
            ],
        ),
    ]
