# Generated by Django 2.2.7 on 2019-11-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HW1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='headquater',
            new_name='headquaters',
        ),
    ]
